name: test_server
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  build_runner: ^2.4.6
  dart_frog: ^1.0.0
  dart_frog_auth: ^1.1.0
  equatable: ^2.0.5
  meta: ^1.11.0
  json_annotation: ^4.8.1
  uuid: ^4.1.0
  crypto: ^3.0.3
  dart_jsonwebtoken: ^2.12.0
  orm: ^3.4.4

dev_dependencies:
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
